apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media-static
resources:
  - namespace.yaml
  - ../base
patches:
  - target:
      kind: Deployment
      name: worker
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 6
