apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: media-worker-cpu-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: worker
  minReplicas: 1
  maxReplicas: 6
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - { type: Pods, value: 2, periodSeconds: 10 }
    scaleDown:
      stabilizationWindowSeconds: 30
      policies:
        - { type: Pods, value: 1, periodSeconds: 15 }
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 65
