apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media-cpu
resources:
  - namespace.yaml
  - ../base
  - hpa.yaml
patches:
  - target:
      kind: ConfigMap
      name: media-config
    patch: |-
      - op: replace
        path: /data/DEPLOYMENT_POLICY
        value: CPU_HPA
