apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media-dynamic
resources:
  - namespace.yaml
  - ../base
  - scaled-object.yaml
patches:
  - target:
      kind: ConfigMap
      name: media-config
    patch: |-
      - op: replace
        path: /data/DEPLOYMENT_POLICY
        value: DYNAMIC
