apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: media-worker-scaler
spec:
  scaleTargetRef:
    name: worker
  pollingInterval: 2
  cooldownPeriod: 30
  minReplicaCount: 1
  maxReplicaCount: 6
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleUp:
          stabilizationWindowSeconds: 0
          policies:
            - { type: Pods, value: 2, periodSeconds: 10 }
        scaleDown:
          stabilizationWindowSeconds: 30
          policies:
            - { type: Pods, value: 1, periodSeconds: 15 }
  triggers:
    - type: redis
      metadata:
        address: redis:6379
        listName: media-processing:pending
        listLength: "5"
        activationListLength: "1"
